/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/table.glb -o src/components/Table.jsx -k -r public
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/table.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Plate" geometry={nodes.Plate.geometry} material={materials.Plate} />
      <mesh name="Legs01Left" geometry={nodes.Legs01Left.geometry} material={materials.Metal} position={[-1.5, 0, 0]} />
      <mesh name="Legs01Right" geometry={nodes.Legs01Right.geometry} material={materials.Metal} position={[1.5, 0, 0]} />
      <mesh name="Legs02Left" geometry={nodes.Legs02Left.geometry} material={materials.Metal} position={[-1.5, 0, 0]} />
      <mesh name="Legs02Right" geometry={nodes.Legs02Right.geometry} material={materials.Metal} position={[1.5, 0, 0]} />
      <mesh name="Legs03Left" geometry={nodes.Legs03Left.geometry} material={materials.Metal} position={[-1.5, 0, 0]} />
      <mesh name="Legs03Right" geometry={nodes.Legs03Right.geometry} material={materials.Metal} position={[1.5, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/table.glb')
